title: <p align="center"> Mark Krickovich </p>

logo: "/assets/img/MK.png?raw=true" 

description:
   <p align="center">
   <font size="+1.5"><b>Finance Quant Turned Data Scientist</b></font>
   </p>
   
   <p align="center">   
   I currently provide Data Science Consulting services with Quantum Analytica.io, a Boston-based firm.
   <br><br>
   </p>

[My LinkedIn Profile]: https://www.linkedin.com/in/markkrickovich/
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

