title: Mark Krickovich
logo: "/assets/img/MK.png?raw=true" 

description:
   ### Finance Quant Turned Data Scientist 
   
   
   I currently provide Data Science 
   Consulting services with Quantum
   Analytica.io, a Boston-based firm.

[My LinkedIn Profile]: https://www.linkedin.com/in/markkrickovich/
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
