title: Mark Krickovich
logo: C:\Users\markk\OneDrive\Pictures\Pictures\Mark
description:
#Finance Quant Turned Data Scientist

#I currently provide Data Science 
#Consulting services with Quantum
#Analytica.io, a Boston-based firm.

(https://www.linkedin.com/in/markkrickovich/ "My LinkedIn Profile")
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
